name: bump version, build artifact, and save to main
on: 
  # whenever a PR is closed against main, or allow manual runs
  workflow_dispatch:
  workflow_run: 
    workflows: ["deploy_bump_version.yml"]
    types:
      - completed




jobs:
  build_artefacts:
    uses: ./.github/workflows/deploy_build_artifact.yaml
    # output:
    #   package-version: ${{ env.VERSION }}
    #   artifact-url: ${{ steps.upload-artifact.artifact-url }}
    #   artifact-id: ${{ steps.upload-artifact.artifact-id }}
    #   build-run-id: ${{ github.run_id }}



  deploy_to_pypi_test:
    needs: [build_artefacts]
    runs-on: ubuntu-latest
    environment: 
      name: 'pypi-test'
    steps:
      - name: download artefact from build run
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4
        with:
          run-id: ${{ needs.build_artefacts.outputs.build-run-id }}
          # run-id: ${{ github.event.inputs.workflow_run_id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: extract artefact
        run: |
          tar -xvf *.tar.gz
      - name: extract version from pyproject.toml
        run: |
          version=$(grep 'version =' pyproject.toml | awk '{print $3}' | sed 's/"//g')
          echo "VERSION=$version" >> $GITHUB_ENV
      - name: Publish package distributions to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
