name: build artifact and publish to PyPi

on:
  workflow_dispatch:
    inputs:
      deploy_to_test:
        type: boolean
        description: 'Deploy to PyPi test'
        required: false
        default: false

env:
  RELEASE_BRANCH: release

jobs:
  validate_branch:
    runs-on: ubuntu-latest
    if: github.ref_name == 'release'
    steps:
      - name: Confirm running on release branch
        run: |
          echo "✅ Running on ${{ env.RELEASE_BRANCH }} branch"
          echo "Current branch: ${{ github.ref_name }}"

  check_wrong_branch:
    runs-on: ubuntu-latest
    if: github.ref_name != 'release'
    steps:
      - name: Fail if not on release branch
        run: |
          echo "❌ ERROR: This workflow can only run on the '${{ env.RELEASE_BRANCH }}' branch!"
          echo ""
          echo "Current branch: ${{ github.ref_name }}"
          echo "Required branch: ${{ env.RELEASE_BRANCH }}"
          echo ""
          echo "This is a safety measure to prevent accidental deployments from non-release branches."
          echo ""
          echo "To deploy, please:"
          echo "  1. Ensure your changes are merged to main"
          echo "  2. Run: gh workflow run sync_release.yml"
          echo "  3. After sync completes, run: gh workflow run deploy_workflow_wrapper.yml --ref ${{ env.RELEASE_BRANCH }}"
          exit 1

  build_artifacts:
    needs: [validate_branch]
    if: github.ref_name == 'release'
    uses: ./.github/workflows/deploy_build_artifact.yaml

  deploy_to_pypi_test:
    needs: [validate_branch, build_artifacts]
    if: github.ref_name == 'release' && github.event.inputs.deploy_to_test == 'true'
    uses: ./.github/workflows/deploy_to_pypi.yml
    with:
      package-version: ${{ needs.build_artifacts.outputs.package-version }}
      target-environment: 'pypi-test'
      artifact-name: ${{ needs.build_artifacts.outputs.artifact-name }}

  deploy_to_pypi_prod_direct:
    needs: [validate_branch, build_artifacts]
    if: github.ref_name == 'release' && github.event.inputs.deploy_to_test != 'true'
    uses: ./.github/workflows/deploy_to_pypi.yml
    with:
      package-version: ${{ needs.build_artifacts.outputs.package-version }}
      target-environment: 'pypi-prod'
      artifact-name: ${{ needs.build_artifacts.outputs.artifact-name }}
