name: build artifact and publish to pypi test
on: 
  # whenever a PR is closed against main, or allow manual runs
  workflow_dispatch:
  workflow_run: 
    workflows: ["bump version"]
    types:
      - completed




jobs:
  build_artefacts:
    uses: ./.github/workflows/deploy_build_artifact.yaml
    # output:
    #   package-version: ${{ env.VERSION }}
    #   artifact-url: ${{ steps.upload-artifact.artifact-url }}
    #   artifact-id: ${{ steps.upload-artifact.artifact-id }}
    #   build-run-id: ${{ github.run_id }}


  # test this here, then move to deploy_to_pypi.yml
  deploy_to_pypi_test:
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    environment: 
      name: 'pypi-test'
    steps:
      - name: download artefact from previous run
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4
        with:
          run-id: ${{ github.event.inputs.workflow_run_id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path: $GITHUB_WORKSPACE/dist
      - name: show files
        run: |
          ls $GITHUB_WORKSPACE/dist
      - name: extract version from pyproject.toml
        run: |
          version=$(grep 'version =' pyproject.toml | awk '{print $3}' | sed 's/"//g')
          echo "VERSION=$version" >> $GITHUB_ENV
          echo "extracted version '{{ $env.VERSION }}' from pyproject.toml"
      - name: Publish package distributions to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          packages-dir: $GITHUB_WORKSPACE/dist
          verbose: true
          print-hash: true
