name: build artifact and publish to PyPi

on:
  workflow_dispatch:
    inputs:
      deploy_to_test:
        type: boolean
        description: 'Deploy to PyPi test'
        required: false
        default: false

jobs:
  validate_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Validate workflow is running on release branch
        run: |
          if [ "${{ github.ref_name }}" != "release" ]; then
            echo "❌ ERROR: This workflow can only run on the 'release' branch!"
            echo ""
            echo "Current branch: ${{ github.ref_name }}"
            echo "Required branch: release"
            echo ""
            echo "This is a safety measure to prevent accidental deployments from non-release branches."
            echo ""
            echo "To deploy, please:"
            echo "  1. Ensure your changes are merged to main"
            echo "  2. Run: gh workflow run sync_release.yml"
            echo "  3. After sync completes, run: gh workflow run deploy_workflow_wrapper.yml --ref release"
            exit 1
          fi
          echo "✅ Running on release branch"

  build_artifacts:
    needs: [validate_branch]
    uses: ./.github/workflows/deploy_build_artifact.yaml

  deploy_to_pypi_test:
    needs: [build_artifacts]
    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.deploy_to_test == 'true' }}
    uses: ./.github/workflows/deploy_to_pypi.yml
    with:
      package-version: ${{ needs.build_artifacts.outputs.package-version }}
      target-environment: 'pypi-test'
      artifact-name: ${{ needs.build_artifacts.outputs.artifact-name }}

  deploy_to_pypi_prod_direct:
    needs: [build_artifacts]
    if: ${{ github.event.inputs.deploy_to_test != 'true' }}
    uses: ./.github/workflows/deploy_to_pypi.yml
    with:
      package-version: ${{ needs.build_artifacts.outputs.package-version }}
      target-environment: 'pypi-prod'
      artifact-name: ${{ needs.build_artifacts.outputs.artifact-name }}
