name: Close Renovate PRs on Success

on:
  workflow_run:
    workflows: ["Run Tests"]
    types:
      - completed

jobs:
  close_pr:
    if: ${{ github.event.workflow_run.conclusion == 'success' }} 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Close PR if tests pass and label exists
        run: |
          PR_NUMBER=$(jq -r '.pull_requests[0].number' < "${{ github.event.workflow_run.pull_requests }}")
          LABELS=$(gh pr view $PR_NUMBER --json labels --jq '.labels[].name')
          if [[ "$LABELS" == *"renovate-pydantic-requests"* ]]; then
            gh pr close $PR_NUMBER --delete-branch
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
